# Book settings
title: Blog
author: UBI Center
logo: ubi_center_logo_wide_blue.svg

html:
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  google_analytics_id       : "UA-138885251-1"
  baseurl                   : "https://blog.ubicenter.org"
  home_page_in_navbar       : false

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

execute:
  execute_notebooks: 'force'
  timeout: -1

launch_buttons:
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/UBICenter/blog
  path_to_book: jb
  branch: master